/**
 * 魚辺（うおへん）のつく漢字 — 海・川・水辺の生き物
 * reading: ひらがな（複数読みは配列）
 */
const KANJI_POOL = [
  { kanji: "鯏", reading: "あさり" },
  { kanji: "鯵", reading: "あじ" },
  { kanji: "鰺", reading: "あじ" },
  { kanji: "鮎", reading: "あゆ" },
  { kanji: "鯇", reading: "あめのうお" },
  { kanji: "鮑", reading: "あわび" },
  { kanji: "鮟", reading: "あんこう" },
  { kanji: "魦", reading: "いさざ" },
  { kanji: "鮖", reading: "いしがきだい" },
  { kanji: "鯆", reading: "いるか" },
  { kanji: "鰯", reading: "いわし" },
  { kanji: "鰛", reading: "いわし" },
  { kanji: "鮇", reading: "いわな" },
  { kanji: "鯎", reading: "うぐい" },
  { kanji: "鱓", reading: "うつぼ" },
  { kanji: "鰻", reading: "うなぎ" },
  { kanji: "鱏", reading: "えい" },
  { kanji: "鱝", reading: "えい" },
  { kanji: "鱛", reading: "えそ" },
  { kanji: "蝦", reading: "えび" },
  { kanji: "鰕", reading: "えび" },
  { kanji: "魵", reading: "えび" },
  { kanji: "鰂", reading: "いか" },
  { kanji: "鰞", reading: "いか" },
  { kanji: "魷", reading: "いか" },
  { kanji: "鮱", reading: "おおぼら" },
  { kanji: "鰧", reading: "おこぜ" },
  { kanji: "鰍", reading: "かじか" },
  { kanji: "鰹", reading: "かつお" },
  { kanji: "鱟", reading: "かぶとがに" },
  { kanji: "魳", reading: "かます" },
  { kanji: "鰈", reading: "かれい" },
  { kanji: "鮍", reading: "かわはぎ" },
  { kanji: "鱚", reading: "きす" },
  { kanji: "鯨", reading: "くじら" },
  { kanji: "鯉", reading: "こい" },
  { kanji: "鯒", reading: "こち" },
  { kanji: "鮗", reading: "このしろ" },
  { kanji: "鮴", reading: ["ごり", "めばる"] },
  { kanji: "鮭", reading: "さけ" },
  { kanji: "鮏", reading: "さけ" },
  { kanji: "鯯", reading: "さっぱ" },
  { kanji: "鯖", reading: "さば" },
  { kanji: "鮫", reading: "さめ" },
  { kanji: "鱵", reading: "さより" },
  { kanji: "鰆", reading: "さわら" },
  { kanji: "鯢", reading: "さんしょううお" },
  { kanji: "鱪", reading: "しいら" },
  { kanji: "鯱", reading: "しゃち" },
  { kanji: "鮊", reading: "しらうお" },
  { kanji: "鯳", reading: "すけとうだら" },
  { kanji: "鱸", reading: "すずき" },
  { kanji: "鯐", reading: "すばしり" },
  { kanji: "鮬", reading: "せいご" },
  { kanji: "鯛", reading: "たい" },
  { kanji: "鰖", reading: "たかべ" },
  { kanji: "鰱", reading: "たなご" },
  { kanji: "鮹", reading: "たこ" },
  { kanji: "魛", reading: "たちうお" },
  { kanji: "鱈", reading: "たら" },
  { kanji: "鱘", reading: "ちょうざめ" },
  { kanji: "鱅", reading: "ちちかぶり" },
  { kanji: "鰌", reading: "どじょう" },
  { kanji: "鯰", reading: "なまず" },
  { kanji: "鰊", reading: "にしん" },
  { kanji: "鰮", reading: "にしん" },
  { kanji: "鮸", reading: "にべ" },
  { kanji: "鯊", reading: "はぜ" },
  { kanji: "鰣", reading: "はす" },
  { kanji: "鰰", reading: "はたはた" },
  { kanji: "魬", reading: "はまち" },
  { kanji: "鱧", reading: "はも" },
  { kanji: "鮠", reading: "はや" },
  { kanji: "鰚", reading: "はらか" },
  { kanji: "鰉", reading: "ひがい" },
  { kanji: "鯷", reading: "ひしこ" },
  { kanji: "鮃", reading: "ひらめ" },
  { kanji: "鰭", reading: "ひれ" },
  { kanji: "鱶", reading: ["ふか", "ふかざめ"] },
  { kanji: "鰒", reading: "ふぐ" },
  { kanji: "鮒", reading: "ふな" },
  { kanji: "鰤", reading: "ぶり" },
  { kanji: "鮪", reading: "まぐろ" },
  { kanji: "鱒", reading: "ます" },
  { kanji: "鮲", reading: "まて" },
  { kanji: "鯧", reading: "まながつお" },
  { kanji: "鯥", reading: "むつ" },
  { kanji: "鰘", reading: "むろあじ" },
  { kanji: "鰙", reading: "わかさぎ" },
  { kanji: "鰐", reading: "わに" },
  { kanji: "鯔", reading: ["いな", "とど", "ぼら"] },
  { kanji: "鱰", reading: "しいら" },
];

/** 2文字以上の水生生物名（読みの重複OK・別エントリとして出題） */
const MULTI_KANJI_POOL = [
  { kanji: "秋刀魚", reading: "さんま" },
  { kanji: "海老", reading: "えび" },
  { kanji: "河豚", reading: "ふぐ" },
  { kanji: "海月", reading: "くらげ" },
  { kanji: "水母", reading: "くらげ" },
  { kanji: "海栗", reading: "うに" },
  { kanji: "海胆", reading: "うに" },
  { kanji: "海星", reading: "ひとで" },
  { kanji: "海盤車", reading: "ひとで" },
  { kanji: "海豚", reading: "いるか" },
  { kanji: "海馬", reading: "とびうお" },
  { kanji: "金魚", reading: "きんぎょ" },
  { kanji: "平目", reading: "ひらめ" },
  { kanji: "太刀魚", reading: "たちうお" },
  { kanji: "石斑魚", reading: "いしがきだい" },
  { kanji: "比目魚", reading: "かれい" },
  { kanji: "岩魚", reading: "いわな" },
  { kanji: "鮎魚", reading: "あゆ" },
  { kanji: "鰻魚", reading: "うなぎ" },
  { kanji: "鮭魚", reading: "さけ" },
  { kanji: "鱒魚", reading: "ます" },
  { kanji: "鯉魚", reading: "こい" },
  { kanji: "鰤魚", reading: "ぶり" },
  { kanji: "鯛魚", reading: "たい" },
  { kanji: "鰈魚", reading: "かれい" },
  { kanji: "鯨魚", reading: "くじら" },
  { kanji: "沙魚", reading: "いさき" },
  { kanji: "目張魚", reading: "かわはぎ" },
  { kanji: "鮟鱇", reading: "あんこう" },
  { kanji: "烏賊", reading: "いか" },
  { kanji: "海鼠", reading: "なまこ" },
  { kanji: "海蛍", reading: "うみほたる" },
  { kanji: "海豹", reading: "あざらし" },
  { kanji: "海獺", reading: "らっこ" },
  { kanji: "海象", reading: "せいうち" },
  { kanji: "海亀", reading: "うみがめ" },
  { kanji: "若鰯", reading: "わかいわし" },
  { kanji: "鱈場蟹", reading: "たらばがに" },
  { kanji: "皇帝蟹", reading: "たらばがに" },
  { kanji: "松葉蟹", reading: "まつばがに" },
  { kanji: "毛蟹", reading: "けがに" },
  { kanji: "沢蟹", reading: "さわがに" },
  { kanji: "岩蟹", reading: "がんがに" },
  { kanji: "梭子蟹", reading: "すられがに" },
  { kanji: "桜海老", reading: "さくらえび" },
  { kanji: "甘海老", reading: "あまえび" },
  { kanji: "伊勢海老", reading: "いせえび" },
  { kanji: "桜鱒", reading: "さくらます" },
  { kanji: "銀鮭", reading: "ぎんざけ" },
  { kanji: "紅鮭", reading: "べにざけ" },
  { kanji: "数の子", reading: "かずのこ" },
  { kanji: "堅魚", reading: "かつお" },
  { kanji: "嘉魚", reading: "いわな" },
  { kanji: "大口魚", reading: "たら" },
  { kanji: "鶏魚", reading: "いさき" },
  { kanji: "鬼蝦", reading: "おにえび" },
  { kanji: "海蛇", reading: "うみへび" },
  { kanji: "川魚", reading: "かわうお" },
  { kanji: "稚魚", reading: "ちぎょ" },
];

function expandPool(pool) {
  const result = [];
  for (const item of pool) {
    const readings = Array.isArray(item.reading) ? item.reading : [item.reading];
    for (const r of readings) {
      result.push({ kanji: item.kanji, reading: [r] });
    }
  }
  return result;
}

const KANJI_SINGLE = expandPool(KANJI_POOL);
const KANJI_MULTI = expandPool(MULTI_KANJI_POOL);
const KANJI_DATABASE = [...KANJI_SINGLE, ...KANJI_MULTI];

function getKanjiPool(mode) {
  if (mode === "single") return KANJI_SINGLE;
  if (mode === "multi") return KANJI_MULTI;
  return KANJI_DATABASE;
}
